### ISSUE TITLE
error

### ISSUE THREAD

**Issue by buxpeng** [wan-h/Brainpower#1]
I'm sorry to bother you here,I saw your answer at maskrcnn-benchmark,I encountered this problem, can you help me with the use of boxlist?Even using bbox[[0]] also made this mistake.thank you very much!
![image](https://user-images.githubusercontent.com/53242456/75760246-ef8e7600-5d71-11ea-8a5c-176b4c4f1f3f.png)

**Comment by wan-h** [comment]
Your picture cannot load, maybe you can contact me by wechat 13658247573

**Comment by wan-h** [comment]
I can get correct result by using bbox[[0]]
